import Head from 'next/head'
import {
  Container,
  Main,
} from '../components/sharedstyles'
import useSWR from 'swr'
import ButtonLink from "../components/ButtonLink"
import AuthorList from "../components/AuthorList"

// General data-fetching function
const fetcher = url => fetch(url).then(r => r.json());

export default function Authors() {
  const { data, error } = useSWR("/api/authors", fetcher);

  // Anytime we fetch data, we want 3 states

  // If the API encounters an error
  if (error) {
    return <Main>
      Error fetching data from API. Sorry :(
    </Main>
  }

  // If the data is loading and has not been resolved yet
  if (!data) {
    return <Main>
      Loading...
    </Main>
  }
  
  const authorToBookCount = {};
  for(const authorName of data) {
    if(!authorToBookCount.hasOwnProperty(authorName)) {
      authorToBookCount[authorName] = 0;
    }
    authorToBookCount[authorName] += 1;
  }
  
  // If the data comes back as expected
  return (
    <Container>
      <Head>
        <title>Betterreads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Betterreads Author List</h1>
        <ButtonLink href="/">Search by Title instead</ButtonLink>
        <AuthorList authorToBookCount={authorToBookCount}></AuthorList>
      </Main>
    </Container>
  )
}
