import Head from 'next/head'
import {
  Container,
  Main,
} from '../components/sharedstyles'
import BookList from '../components/BookList'
import useSWR from 'swr'
import ButtonLink from "../components/ButtonLink"

// General data-fetching function
const fetcher = url => fetch(url).then(r => r.json());

export default function Home() {
  const { data, error } = useSWR("/api/books", fetcher);
  
  // Anytime we fetch data, we want 3 states
  
  // If the API encounters an error
  if(error) {
    return <Main>
      Error fetching data from API. Sorry :(
    </Main>
  }
  
  // If the data is loading and has not been resolved yet
  if(!data) {
    return <Main>
      Loading...
    </Main>
  }
  
  // If the data comes back as expected
  return (
    <Container>
      <Head>
        <title>Betterreads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Betterreads Book List</h1>
        <p><ButtonLink href="/author">Search by Author instead</ButtonLink></p>
        <BookList books={data}></BookList>
      </Main>
    </Container>
  )
}
